### ISSUE TITLE
Areas without data should be colored consistently.

### ISSUE THREAD

**Issue by tildechris** [google-research/vaccination-search-insights#130]
We used to color "0", which should be "N/A", white.  When ZCTAs were implemented zip regions without data were colored gray.  This lead to a situation where both white and gray regions can be seen.  We need to be consistent.

![image](https://user-images.githubusercontent.com/46794497/127697213-9fdc47c3-1ccb-478e-948a-bb818028bf1f.png)

**Comment by guiballs415** [comment]
Hovercards also need to reflect missing data. There's two cases ...
(1) Some (but not all) of the categories are missing data
(2) There's not data for any of the categories
Here's mocks of the corresponding hovercards ...
![image](https://user-images.githubusercontent.com/71027206/127703870-2d5e91f1-8797-4a5d-a008-140cf900a04e.png)
